// <auto-generated />
using System;
using CineMatch.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CineMatch.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521103819_AddIsStartedToWatchParty")]
    partial class AddIsStartedToWatchParty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CineMatch.Domain.Models.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsWatched")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("MatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WatchPartyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("WatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WatchedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("WatchedByUserId");

                    b.HasIndex("WatchPartyId", "MovieId")
                        .IsUnique();

                    b.ToTable("Matches", (string)null);
                });

            modelBuilder.Entity("CineMatch.Domain.Models.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TmdbId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TmdbId")
                        .IsUnique();

                    b.ToTable("Movies", (string)null);
                });

            modelBuilder.Entity("CineMatch.Domain.Models.PartyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WatchPartyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WatchPartyId");

                    b.HasIndex("UserId", "WatchPartyId")
                        .IsUnique();

                    b.ToTable("PartyMembers", (string)null);
                });

            modelBuilder.Entity("CineMatch.Domain.Models.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("CineMatch.Domain.Models.Swipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsLiked")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PartyMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SwipedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WatchPartyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("WatchPartyId");

                    b.HasIndex("PartyMemberId", "MovieId")
                        .IsUnique();

                    b.ToTable("Swipes", (string)null);
                });

            modelBuilder.Entity("CineMatch.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsEmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CineMatch.Domain.Models.WatchParty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStarted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HostId");

                    b.HasIndex("JoinCode")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = true");

                    b.ToTable("WatchParties", (string)null);
                });

            modelBuilder.Entity("CineMatch.Domain.Models.WatchPartyMovie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("WatchPartyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("WatchPartyId", "MovieId")
                        .IsUnique();

                    b.HasIndex("WatchPartyId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("WatchPartyMovies", (string)null);
                });

            modelBuilder.Entity("CineMatch.Domain.Models.Match", b =>
                {
                    b.HasOne("CineMatch.Domain.Models.Movie", "Movie")
                        .WithMany("Matches")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CineMatch.Domain.Models.WatchParty", "WatchParty")
                        .WithMany("Matches")
                        .HasForeignKey("WatchPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CineMatch.Domain.Models.User", "WatchedBy")
                        .WithMany("WatchedMatches")
                        .HasForeignKey("WatchedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Movie");

                    b.Navigation("WatchParty");

                    b.Navigation("WatchedBy");
                });

            modelBuilder.Entity("CineMatch.Domain.Models.PartyMember", b =>
                {
                    b.HasOne("CineMatch.Domain.Models.User", "User")
                        .WithMany("PartyMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CineMatch.Domain.Models.WatchParty", "WatchParty")
                        .WithMany("PartyMembers")
                        .HasForeignKey("WatchPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WatchParty");
                });

            modelBuilder.Entity("CineMatch.Domain.Models.PasswordResetToken", b =>
                {
                    b.HasOne("CineMatch.Domain.Models.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CineMatch.Domain.Models.Swipe", b =>
                {
                    b.HasOne("CineMatch.Domain.Models.Movie", "Movie")
                        .WithMany("Swipes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CineMatch.Domain.Models.PartyMember", "PartyMember")
                        .WithMany("Swipes")
                        .HasForeignKey("PartyMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CineMatch.Domain.Models.WatchParty", "WatchParty")
                        .WithMany("Swipes")
                        .HasForeignKey("WatchPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("PartyMember");

                    b.Navigation("WatchParty");
                });

            modelBuilder.Entity("CineMatch.Domain.Models.WatchParty", b =>
                {
                    b.HasOne("CineMatch.Domain.Models.User", "Host")
                        .WithMany("WatchPartiesHosted")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Host");
                });

            modelBuilder.Entity("CineMatch.Domain.Models.WatchPartyMovie", b =>
                {
                    b.HasOne("CineMatch.Domain.Models.Movie", "Movie")
                        .WithMany("WatchPartyMovies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CineMatch.Domain.Models.WatchParty", "WatchParty")
                        .WithMany("WatchPartyMovies")
                        .HasForeignKey("WatchPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("WatchParty");
                });

            modelBuilder.Entity("CineMatch.Domain.Models.Movie", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Swipes");

                    b.Navigation("WatchPartyMovies");
                });

            modelBuilder.Entity("CineMatch.Domain.Models.PartyMember", b =>
                {
                    b.Navigation("Swipes");
                });

            modelBuilder.Entity("CineMatch.Domain.Models.User", b =>
                {
                    b.Navigation("PartyMemberships");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("WatchPartiesHosted");

                    b.Navigation("WatchedMatches");
                });

            modelBuilder.Entity("CineMatch.Domain.Models.WatchParty", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("PartyMembers");

                    b.Navigation("Swipes");

                    b.Navigation("WatchPartyMovies");
                });
#pragma warning restore 612, 618
        }
    }
}
